name: u64_array_bigints CI

on: [pull_request]

env:
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1

jobs:
  test_suite:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # need nightly for `cargo bench`
      - name: Install Rust components
        run: |
          rustup set profile minimal
          rustup default nightly
      - name: Run test suite
        run: |
          cargo bench --no-default-features --features=rand_support,serde_support
          cargo bench --all-features
          cargo test --no-default-features --features=rand_support,serde_support
          cargo test --all-features
          cargo test --release

  miri:
    name: Miri
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      MIRIFLAGS: -Zmiri-strict-provenance
    steps:
      - uses: actions/checkout@v2
      - name: Install most recent Miri
        run: |
          rustup set profile minimal
          rustup default "nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)"
          rustup component add miri
      - name: Run test suite with Miri
        run: |
          cargo miri test --no-default-features --features=rand_support,serde_support
          cargo miri test --all-features

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Acquire the most recent nightly with a rustfmt component
      - name: Install most recent Rustfmt
        run: |
          rustup set profile minimal
          rustup default "nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/rustfmt)"
          rustup component add rustfmt
      - name: Run `cargo fmt`
        run: |
          cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Acquire the most recent nightly with a clippy component
      - name: Install most recent Clippy
        run: |
          rustup set profile minimal
          rustup default "nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/clippy)"
          rustup component add clippy
      - name: Run `cargo clippy`
        run: |
          cargo clippy --all --all-targets --no-default-features --features=rand_support,serde_support -- -D clippy::all
          cargo clippy --all --all-targets --all-features -- -D clippy::all

  # makes sure the tests work on 32 bit and 64 bit big endian targets
  cross-compile-big-endian:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cross-compile-mips
      run: |
        cargo install cross
        cross test --target mips64-unknown-linux-gnuabi64 --no-default-features --features=rand_support,serde_support
        cross test --target mips64-unknown-linux-gnuabi64 --all-features
        cross test --target mips-unknown-linux-gnu --no-default-features --features=rand_support,serde_support
        cross test --target mips-unknown-linux-gnu --all-features
